### ISSUE TITLE
Adding XCM to ink! V6 contract leads to Result ModuleError: Revive::CodeRejected Error

### ISSUE THREAD

**Issue by N1ghtStorm** [use-ink/ink#2526]
Simple ink! V6 contract example (contract compiles with `cargo contract build --release` without any error)

``` Rust
#![cfg_attr(not(feature = "std"), no_std, no_main)]

#[ink::contract]
mod testxcm {
    use ink::U256;

    pub type Result<T> = core::result::Result<T, Error>;

    #[derive(Debug, PartialEq, Eq)]
    #[ink::scale_derive(Encode, Decode, TypeInfo)]
    pub enum Error {
        XcmSendFailed,
    }

    /// Defines the storage of your contract.
    /// Add new fields to the below struct in order
    /// to add new static storage fields to your contract.
    #[ink(storage)]
    pub struct Testxcm {}

    impl Testxcm {
        /// Constructor that initializes the `bool` value to the given `init_value`.
        #[ink(constructor)]
        pub fn new() -> Self {
            Self {}
        }

        #[ink(message)]
        pub fn test_xcm(&mut self, beneficiary: [u8; 32]) -> Result<()> {
            use ink::xcm::v4::{Asset, Junctions::Here, Location, Parent, WeightLimit, Xcm};

            let value = self.env().balance();
            let value_32: u128 = value.try_into().unwrap();

            let fee: u128 = U256::from(1000000000).try_into().unwrap();

            let destination: Location = Parent.into();

            let assets: Asset = (Here, value_32).into();

            let beneficiary: Location = ink::xcm::v4::Junction::AccountId32 {
                network: None,
                id: beneficiary,
            }
            .into();

            let message: Xcm<()> = Xcm::builder()
                .withdraw_asset(assets.clone())
                .buy_execution((Here, fee), WeightLimit::Unlimited)
                .deposit_asset(assets, beneficiary)
                .build();

            let res = self.env().xcm_send(
                &ink::xcm::VersionedLocation::V4(destination),
                &ink::xcm::VersionedXcm::V4(message),
            );

            if res.is_err() {
                return Err(Error::XcmSendFailed);
            }

            Ok(())
        }
    }
}

```

Cargo.toml

```toml
[package]
name = "testxcm"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2021"

[dependencies]
ink = { version = "6.0.0-alpha", default-features = false, features = ["unstable-hostfn"] }

[dev-dependencies]
ink_e2e = "6.0.0-alpha"
scale-info = { version = "2.6.0", default-features = false, features = ["derive"] }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
]
ink-as-dependency = []
e2e-tests = []

```
trying to deploy it via cargo contract upload leads to error:

```bash
Result ModuleError: Revive::CodeRejected: ["The contract failed to compile or is missing the correct entry points.", "", "A more detailed error can be found on the node console if debug messages are enabled", "by supplying `-lruntime::revive=debug`."]
```

got the same error using https://inkv6alpha.netlify.app/instantiate

```
CodeRejected
The contract failed to compile or is missing the correct entry points.A more detailed error can be found on the node console if debug messages are enabledby supplying `-lruntime::revive=debug`.
```

commenting these lines fixes the problem

```rust

            // let res = self.env().xcm_send(
            //     &ink::xcm::VersionedLocation::V4(destination),
            //     &ink::xcm::VersionedXcm::V4(message),
            // );
```

 Rust toolchain and version (also tested on 1.86)
```
 stable-aarch64-apple-darwin - rustc 1.87.0 (17067e9ac 2025-05-09)

```
 Cargo contract version
```
cargo-contract-contract 6.0.0-alpha-unknown-aarch64-apple-darwin
```
